motd: "&4Super duper Server!"

database:
  host: "localhost"
  port: 3307
  database: "minecraft"
  username: "mcuser"
  password: "mcuser"

  pool:
    maximum-pool-size: 10
    minimum-idle: 2
    connection-timeout: 30000